### ISSUE TITLE
[Bug] Shortcuts not working on OSX 10.10.5 Yosemite

### ISSUE THREAD

**Issue by github-throwaway** [palaniraja/speedy#1]
Hey,
I love your app. However, it seems that all shortcut available via the Options menu are not working. They are greyed out and the shortcuts themselves dont work as well.

<img width="221" alt="screen shot 2018-07-31 at 11 58 20" src="https://user-images.githubusercontent.com/25488086/43452977-5689bb88-94a8-11e8-8203-06263c4eb915.png">

Cheers

**Comment by palaniraja** [comment]
Thank you.

Are you on [latest version](https://github.com/palaniraja/speedy/releases/tag/v1.7)? I remember fixing it. Let me know if it still having issue.

The old issue was though it looks like disabled, it worked with annoying mac error sound.

Unfortunately I do not have access to Yosemite, the latest version works with Sierra (10.12.6 - my current machine). I'll have a look at it again soon.

**Comment by github-throwaway** [comment]
Yes, I am using the latest version 1.7

The other shortcuts (skipping words for example or the global hotkey for 
launching the app) are working as you said with the annoying mac sound.

Thanks for looking into it. :)

**Comment by palaniraja** [comment]
Hi,

I have finally managed to rebuild (v1.8) with few more fixes. Unfortunately I still do not have access to 10.10.5. 

https://github.com/palaniraja/speedy/releases/tag/v1.8

I think I have fixed the disabled _option_ menu items, could not verify. However the annoying beep when you forward/rewind text is definitely fixed now.

Please test and let me know the status. 

Have a great day.

**Comment by github-throwaway** [comment]
As far as I can tell everything is working like a charm! Thanks for taking the time to develop a fix. Much appreciated! :)

**Comment by palaniraja** [comment]
Glad it worked 👍
